# Generated by Django 4.2.8 on 2024-02-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=1500, verbose_name='Статья')),
                ('rating', models.IntegerField()),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
            ],
        ),
    ]
