# Generated by Django 4.2.8 on 2024-02-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_post_date_create_alter_post_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='simple',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
